server:
  port: 8767

spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /bsns1/**
      serviceId: business-1
    api-b:
      path: /bsns2/**
      serviceId: business-2